language: node_js

node_js:
  - 0.12
  - 4.1

services: mongodb

install: npm install --loglevel silent

script: npm test

after_success: npm run coveralls

notifications:
  email:
    on_failure: change
    on_success: change
